#!/bin/bash
#
#
# Version 0.1
#
# chkconfig: - 79 21
# description: numadio is service what filter twitter time line.

if [ -f /usr/local/etc/numadio ]; then
	. /usr/local/etc/numadio
fi

prog=numadio
RETVAL=0
cd `dirname $0`
CUR_DIR=`pwd`

start() {
	echo -n $"Starting ${prog}:"

	jsvc  -home ${JAVA_HOME} -cp ${CLASSPATH}:${NUMADIO}/* -pidfile ${NUMADIO_PID} ${NUMADIO_MAIN} ${CUR_DIR}
	RETVAL=$?
	if [[ $RETVAL == 0 ]]; then
		echo -e "\t\t [\033[1;32m  OK  \033[0m]"
	else
		echo -e "\t\t [\033[1;31m  FAILED  \033[0m]"
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping ${prog}"

	jsvc  -stop -pidfile ${NUMADIO_PID} ${NUMADIO_MAIN}
	RETVAL=$?
	if [[ $RETVAL == 0 ]]; then
		echo -e "\t\t [\033[1;32m  OK  \033[0m]"
	else
		echo -e "\t\t [\033[1;31m  FAILED  \033[0m]"
	fi
	return $RETVAL
}

case "$1" in
	start)
	start
	;;
	stop)
	stop
	;;
	restart)
	stop
	start
	;;
	*)
	echo $"Usage: ${prog} {start|top}"
	RETVAL=2
esac

exit $RETVAL